// ============================================================
// 船用英语（航运 / 货代 / 船代）词库
// 结构：U1–U10 单词单元，每单元 100 词（按工作常用度从高到低）；
//       U11–U15 邮件/文件短语单元，每单元 60 条。
// 由下方 SHIP_UNITS 展开为 SHIP_BOOK / SHIP_WORDS（与王陆同构），
// 学习/测试/错题本/重要单词全部复用主站现有逻辑（与六级一致）。
// 本文件不修改也不依赖 data.js / wanglu_data.js / scene_data.js。
// ============================================================
window.SHIP_VERSION = 1;
window.SHIP_UNITS = [
  { kind: 'word', name: 'Unit 1 · 最常用核心词（订舱/船期/单据/费用）', list: [
    ['shipment', '装运；一批货物'],
    ['cargo', '货物；船货'],
    ['shipping', '航运；海运'],
    ['vessel', '船舶'],
    ['carrier', '承运人；船公司'],
    ['shipper', '托运人；发货人'],
    ['consignee', '收货人'],
    ['forwarder', '货运代理（货代）'],
    ['agent', '代理；代理人'],
    ['liner', '班轮；定期船'],
    ['freight', '运费；货物'],
    ['rate', '运价；费率'],
    ['quotation', '报价单；报价'],
    ['quote', '报价'],
    ['booking', '订舱；预订'],
    ['sailing', '开航；船期'],
    ['schedule', '船期表；时间表'],
    ['voyage', '航次；航程'],
    ['route', '航线；路线'],
    ['port', '港口'],
    ['destination', '目的港；目的地'],
    ['origin', '起运地；原产地'],
    ['transshipment', '转运；中转'],
    ['delivery', '交货；交付'],
    ['pickup', '提货；提取'],
    ['container', '集装箱'],
    ['bill of lading', '提单（B/L）'],
    ['invoice', '发票'],
    ['packing list', '装箱单'],
    ['customs', '海关'],
    ['clearance', '清关；结关'],
    ['duty', '关税；税'],
    ['insurance', '保险'],
    ['claim', '索赔；理赔'],
    ['delay', '延误；延迟'],
    ['ETA', '预计抵达时间', 'estimated time of arrival'],
    ['ETD', '预计离港时间', 'estimated time of departure'],
    ['arrival', '到达；抵达'],
    ['departure', '离港；出发'],
    ['loading', '装货；装载'],
    ['unloading', '卸货'],
    ['demurrage', '滞期费'],
    ['detention', '滞箱费；扣箱费'],
    ['free time', '免费用箱期'],
    ['storage', '仓储；堆存费'],
    ['charge', '费用；收费'],
    ['surcharge', '附加费'],
    ['payment', '付款；支付'],
    ['payable', '应付的；应付款'],
    ['document', '文件；单据'],
    ['copy', '副本；复印件'],
    ['original', '正本'],
    ['confirm', '确认'],
    ['advise', '通知；告知'],
    ['notify', '通知；告知'],
    ['party', '当事方；一方'],
    ['account', '账户；账目'],
    ['company', '公司'],
    ['office', '办公室；办事处'],
    ['branch', '分公司；分部'],
    ['customer', '客户'],
    ['supplier', '供应商'],
    ['buyer', '买方'],
    ['seller', '卖方'],
    ['exporter', '出口商'],
    ['importer', '进口商'],
    ['trade', '贸易'],
    ['contract', '合同'],
    ['order', '订单；订购'],
    ['quantity', '数量'],
    ['weight', '重量'],
    ['volume', '体积；容积'],
    ['measurement', '尺码；尺寸'],
    ['unit', '单位'],
    ['price', '价格'],
    ['value', '价值；金额'],
    ['currency', '货币'],
    ['exchange rate', '汇率'],
    ['valid', '有效的'],
    ['invalid', '无效的'],
    ['amend', '修改；修正'],
    ['change', '变更；更改'],
    ['cancel', '取消'],
    ['re-book', '重新订舱'],
    ['space', '舱位'],
    ['allocate', '分配；配给'],
    ['available', '可用的；有舱位的'],
    ['full', '满的；满载的'],
    ['vessel name', '船名'],
    ['voyage number', '航次号'],
    ['container number', '箱号'],
    ['seal number', '封条号'],
    ['place of receipt', '收货地'],
    ['port of loading', '装货港'],
    ['port of discharge', '卸货港'],
    ['place of delivery', '交货地'],
    ['final destination', '最终目的地'],
    ['on board', '已装船'],
    ['received for shipment', '收妥待运'],
    ['shipped on board', '已装船（提单批注）'],
    ['clean', '清洁的（清洁提单）'],
    ['telex release', '电放'],
    ['express release', '快放；即时放货']
  ]},
  { kind: 'word', name: 'Unit 2 · 订舱/操作/箱管常用词', list: [
    ['booking confirmation', '订舱确认（S/O 确认）'],
    ['shipping order', '装货单；下货纸（S/O）'],
    ['booking note', '订舱单'],
    ['cargo space', '舱位；货位'],
    ['cut-off time', '截关时间；截单时间'],
    ['closing date', '截关日期'],
    ['cancellation', '取消'],
    ['late booking', '晚订舱；临时订舱'],
    ['rebooking', '重新订舱'],
    ['roll over', '延至下一航次（甩柜）'],
    ['rolled cargo', '被甩下的货物'],
    ['waiting list', '候补名单'],
    ['subject to', '以……为准；视……而定'],
    ['subject to space', '以有舱位为准'],
    ['shut out', '退关；甩柜'],
    ['vessel schedule', '船期表'],
    ['sailing schedule', '船期表'],
    ['transit time', '运输时间；在途时间'],
    ['loading date', '装船日期'],
    ['sailing date', '开船日期'],
    ['arrival date', '抵达日期'],
    ['estimated time of arrival', '预计抵达时间（ETA）'],
    ['estimated time of departure', '预计离港时间（ETD）'],
    ['estimated time of sailing', '预计开航时间（ETS）'],
    ['laytime', '装卸时间；受载期'],
    ['deadline', '截止时间；最后期限'],
    ['on schedule', '按船期；准时'],
    ['behind schedule', '晚于船期'],
    ['ahead of schedule', '早于船期'],
    ['delay shipment', '延迟装运'],
    ['expedite', '加快；加速（办理）'],
    ['rush', '加急；催促'],
    ['urgent', '紧急的'],
    ['immediate', '立即的；即时的'],
    ['as soon as possible', '尽快（ASAP）'],
    ['please note', '请注意'],
    ['kindly', '请（客气用法）'],
    ['regarding', '关于'],
    ['concerning', '关于'],
    ['with reference to', '关于；就……而言'],
    ['in accordance with', '按照；依照'],
    ['per', '每；按照'],
    ['according to', '根据'],
    ['in case of', '如果发生……；万一'],
    ['in the event of', '如果发生……'],
    ['due to', '由于'],
    ['owing to', '由于'],
    ['because of', '因为'],
    ['except', '除……之外'],
    ['including', '包括'],
    ['excluding', '不包括；除外'],
    ['between', '在……之间'],
    ['within', '在……之内'],
    ['before', '在……之前'],
    ['after', '在……之后'],
    ['until', '直到'],
    ['from...to...', '从……到……'],
    ['attach', '附上；随附'],
    ['attached', '随附的'],
    ['enclosure', '附件'],
    ['attachment', '附件'],
    ['herewith', '随函；随信'],
    ['hereby', '特此；兹'],
    ['thereby', '由此；从而'],
    ['thereof', '其；其中'],
    ['thereafter', '此后'],
    ['aforementioned', '上述的'],
    ['above-mentioned', '上述的'],
    ['below', '下列；如下'],
    ['following', '下列的'],
    ['as follows', '如下'],
    ['enclose', '随信附上'],
    ['find attached', '随函附上（请查收附件）'],
    ['see attached', '请见附件'],
    ['refer to', '参考；参见'],
    ['enclosed please find', '随函附上……请查收'],
    ['by return', '尽快回复'],
    ['at your earliest convenience', '尽早（在您方便时尽快）'],
    ['awaiting your reply', '等待您的回复'],
    ['look forward to', '期待'],
    ['hear from you', '收到您的回复'],
    ['best regards', '此致敬意（邮件结尾）'],
    ['kind regards', '此致敬意（邮件结尾）'],
    ['yours sincerely', '谨上（邮件结尾）'],
    ['thank you for', '感谢您……'],
    ['thanks for your email', '感谢您的来信'],
    ['we are pleased to', '我们很高兴……'],
    ['we regret to', '我们很遗憾……'],
    ['we apologize for', '我们为……道歉'],
    ['sorry for the delay', '对延误表示歉意'],
    ['could you please', '您能否……（请……）'],
    ['would you please', '请您……好吗'],
    ['please kindly', '请（客气请求）'],
    ['please be advised', '特此通知'],
    ['this is to inform you', '此函通知您'],
    ['we would like to', '我们想……'],
    ['we wish to', '我们希望……'],
    ['please arrange', '请安排'],
    ['please advise', '请告知'],
    ['please confirm', '请确认'],
    ['please check', '请核对'],
    ['please double check', '请再核对一遍']
  ]},
  { kind: 'word', name: 'Unit 3 · 单证/提单/报关/贸易文件', list: [
    ['shipping documents', '装运单据'],
    ['sea waybill', '海运单（不可转让）'],
    ['house bill of lading', '货代提单（HBL）'],
    ['master bill of lading', '主提单；船东提单（MBL）'],
    ['ocean bill of lading', '海运提单（OBL）'],
    ['original bill of lading', '正本提单'],
    ['surrender', '交回；提交（正本）'],
    ['endorse', '背书'],
    ['endorsement', '背书'],
    ['endorsed', '已背书的'],
    ['negotiable', '可转让的'],
    ['non-negotiable', '不可转让的'],
    ['to order', '凭指示（提单抬头）'],
    ['bearer', '持票人；持有人'],
    ['consign', '托运；寄运'],
    ['consignment', '托运的货物；寄售'],
    ['straight bill of lading', '记名提单'],
    ['order bill of lading', '指示提单'],
    ['blank endorsed', '空白背书'],
    ['date of issue', '签发日期'],
    ['place of issue', '签发地点'],
    ['issue', '签发；出具'],
    ['issued', '已签发的'],
    ['re-issue', '重新签发'],
    ['replace', '替换'],
    ['replacement', '替换件；补发'],
    ['lost bill of lading', '遗失提单'],
    ['letter of indemnity', '保函（LOI）'],
    ['indemnity', '赔偿；补偿'],
    ['indemnify', '赔偿'],
    ['declare', '申报；声明'],
    ['declaration', '申报；报关单'],
    ['customs declaration', '报关单'],
    ['customs broker', '报关行'],
    ['broker', '经纪人；报关代理'],
    ['customs broker fee', '报关费'],
    ['customs inspection', '海关查验'],
    ['customs examination', '海关查验'],
    ['inspection', '查验；检验'],
    ['examination', '检查；查验'],
    ['release', '放行'],
    ['released', '已放行的'],
    ['customs release', '海关放行'],
    ['customs clearance fee', '清关费'],
    ['customs bond', '海关保证金'],
    ['bonded', '保税的'],
    ['bonded warehouse', '保税仓库'],
    ['bonded area', '保税区'],
    ['free trade zone', '自由贸易区'],
    ['drawback', '退税；出口退税'],
    ['refund', '退款；退税'],
    ['tariff', '关税；税率表'],
    ['tariff rate', '关税率'],
    ['tax', '税'],
    ['taxable', '应纳税的'],
    ['tax-exempt', '免税的'],
    ['value added tax', '增值税（VAT）'],
    ['import duty', '进口关税'],
    ['export duty', '出口关税'],
    ['anti-dumping duty', '反倾销税'],
    ['commodity', '商品；货物'],
    ['commodity inspection', '商品检验'],
    ['certificate', '证书'],
    ['certificate of origin', '原产地证书（CO）'],
    ['inspection certificate', '检验证书'],
    ['health certificate', '健康证书；卫生证书'],
    ['phytosanitary certificate', '植物检疫证书'],
    ['quarantine', '检疫'],
    ['license', '许可证'],
    ['import license', '进口许可证'],
    ['export license', '出口许可证'],
    ['permit', '许可；许可证'],
    ['proforma invoice', '形式发票'],
    ['commercial invoice', '商业发票'],
    ['customs invoice', '海关发票'],
    ['credit note', '贷项通知单'],
    ['debit note', '借项通知单'],
    ['statement', '对账单；账单'],
    ['receipt', '收据'],
    ['voucher', '凭证'],
    ['certificate of analysis', '分析证书（COA）'],
    ['certificate of insurance', '保险凭证'],
    ['policy', '保险单'],
    ['open policy', '预约保险单'],
    ['warehouse receipt', '仓单'],
    ['delivery order', '提货单（D/O）'],
    ['dock receipt', '码头收据'],
    ['mate\'s receipt', '大副收据'],
    ['tally', '理货'],
    ['tally sheet', '理货单'],
    ['manifest', '舱单'],
    ['cargo manifest', '货物舱单'],
    ['container manifest', '集装箱舱单'],
    ['booking confirmation note', '订舱确认单'],
    ['shipping instruction', '装运指示；补料'],
    ['shipping advice', '装运通知'],
    ['shipping note', '装货通知'],
    ['freight invoice', '运费发票'],
    ['freight receipt', '运费收据'],
    ['delivery note', '交货单'],
    ['waybill', '运单'],
    ['air waybill', '空运单（AWB）'],
    ['rail waybill', '铁路运单'],
    ['combined transport document', '多式联运单据']
  ]},
  { kind: 'word', name: 'Unit 4 · 港口/码头/集装箱/堆场/陆运', list: [
    ['seaport', '海港'],
    ['harbour', '港口；港湾'],
    ['terminal', '码头；码头作业区'],
    ['container terminal', '集装箱码头'],
    ['berth', '泊位；停泊'],
    ['quay', '码头岸壁'],
    ['pier', '突堤码头'],
    ['wharf', '码头'],
    ['jetty', '栈桥码头'],
    ['anchorage', '锚地'],
    ['anchorage area', '锚泊区'],
    ['mooring', '系泊'],
    ['alongside', '靠泊；在船舷边'],
    ['alongside ship', '船边'],
    ['gangway', '舷梯'],
    ['pilot', '引航员'],
    ['pilotage', '引航；引航费'],
    ['tugboat', '拖船'],
    ['tug', '拖轮'],
    ['barge', '驳船'],
    ['feeder', '支线船；转运船'],
    ['mother vessel', '母船'],
    ['coastal ship', '沿海船'],
    ['deep sea vessel', '远洋船'],
    ['ocean-going vessel', '远洋船舶'],
    ['reefer', '冷藏集装箱；冷藏船'],
    ['reefer container', '冷藏箱'],
    ['open top container', '开顶箱'],
    ['flat rack container', '框架箱'],
    ['tank container', '罐式集装箱'],
    ['bulk container', '散装集装箱'],
    ['dry container', '干货箱'],
    ['general purpose container', '通用集装箱'],
    ['high cube container', '高箱（HQ）'],
    ['standard container', '标准箱'],
    ['empty container', '空箱'],
    ['loaded container', '重箱；已装货箱'],
    ['full container load', '整箱货（FCL）'],
    ['less than container load', '拼箱货（LCL）'],
    ['container yard', '集装箱堆场（CY）'],
    ['container freight station', '集装箱货运站（CFS）'],
    ['depot', '堆场；仓库'],
    ['container depot', '集装箱堆场'],
    ['empty container depot', '空箱堆场'],
    ['return empty', '归还空箱'],
    ['drop off', '交箱；还箱'],
    ['gate in', '进港（重箱进场）'],
    ['gate out', '出闸；提箱出场'],
    ['stuffing', '装箱（装柜）'],
    ['stripping', '拆箱'],
    ['unstuffing', '拆箱'],
    ['devanning', '拆箱'],
    ['vanning', '装箱'],
    ['lashing', '绑扎'],
    ['lashing material', '绑扎材料'],
    ['chocking', '塞垫'],
    ['dunnage', '垫舱物料；垫料'],
    ['seaworthy packing', '适航包装'],
    ['packing', '包装'],
    ['package', '件；包装件'],
    ['pallet', '托盘'],
    ['palletized', '托盘化的'],
    ['carton', '纸箱'],
    ['case', '箱；木箱'],
    ['crate', '板条箱'],
    ['drum', '桶'],
    ['barrel', '桶'],
    ['bag', '袋'],
    ['bale', '包（捆包）'],
    ['roll', '卷'],
    ['coil', '卷；卷材'],
    ['sheet', '板材；薄板'],
    ['slab', '厚板'],
    ['bundle', '捆'],
    ['loose cargo', '散件货；裸装货'],
    ['bulk cargo', '散装货'],
    ['liquid cargo', '液体货'],
    ['dangerous cargo', '危险货物'],
    ['hazardous goods', '危险品'],
    ['perishable goods', '易腐货物'],
    ['refrigerated cargo', '冷藏货物'],
    ['oversized cargo', '超尺寸货物'],
    ['overweight cargo', '超重货物'],
    ['out of gauge cargo', '超限货物（OOG）'],
    ['breakbulk cargo', '件杂货'],
    ['general cargo', '杂货；一般货物'],
    ['unitized cargo', '成组化货物'],
    ['project cargo', '项目货'],
    ['rolling cargo', '滚装货物'],
    ['accompanied cargo', '随车货物'],
    ['bonded cargo', '保税货物'],
    ['transit cargo', '过境货物'],
    ['through cargo', '联运货物'],
    ['transshipment cargo', '转运货物'],
    ['returned cargo', '退运货物'],
    ['consolidated cargo', '拼箱货物'],
    ['household goods', '搬家物品'],
    ['personal effects', '个人物品'],
    ['equipment', '设备'],
    ['machinery', '机械设备'],
    ['spare parts', '备件；零部件'],
    ['chemicals', '化学品'],
    ['steel products', '钢材产品'],
    ['grain', '谷物'],
    ['coal', '煤炭'],
    ['ore', '矿石'],
    ['crude oil', '原油'],
    ['petroleum products', '石油产品'],
    ['liquefied natural gas', '液化天然气（LNG）'],
    ['cement', '水泥'],
    ['fertilizer', '化肥'],
    ['timber', '木材']
  ]},
  { kind: 'word', name: 'Unit 5 · 运价/计费/财务/结算', list: [
    ['freight rate', '运费率；运价'],
    ['base rate', '基本运费率'],
    ['basic freight', '基本运费'],
    ['all-in rate', '全包价费率'],
    ['all-in', '全包的；一价全含'],
    ['ocean freight rate', '海运费率'],
    ['sea freight', '海运费'],
    ['air freight', '空运费'],
    ['land freight', '陆运费'],
    ['rail freight', '铁路运费'],
    ['inland freight', '内陆运费'],
    ['trucking charge', '拖车费；卡车运费'],
    ['cartage', '搬运费'],
    ['haulage', '拖运费；公路运输费'],
    ['drayage', '拖箱费'],
    ['terminal handling charge', '码头操作费（THC）'],
    ['port handling charge', '港口操作费'],
    ['handling charge', '操作费；装卸费'],
    ['documentation fee', '文件费；单证费'],
    ['document fee', '单证费'],
    ['booking fee', '订舱费'],
    ['amendment fee', '改单费'],
    ['change fee', '改单费'],
    ['cancellation fee', '取消费'],
    ['seal fee', '封条费'],
    ['customs clearance charge', '报关费'],
    ['inspection fee', '查验费'],
    ['storage fee', '堆存费'],
    ['warehouse charge', '仓储费'],
    ['container usage charge', '用箱费'],
    ['equipment usage charge', '设备使用费'],
    ['container imbalance charge', '箱使费；用箱不平衡费'],
    ['repositioning charge', '调箱费'],
    ['empty repositioning fee', '空箱调运费'],
    ['lift on lift off', '吊上吊下费（LOLO）'],
    ['lift on charge', '吊装费（装箱上船）'],
    ['lift off charge', '吊卸费'],
    ['wharfage', '码头使用费'],
    ['wharfage charge', '码头费'],
    ['pier charge', '码头费'],
    ['dockage', '船坞费；码头费'],
    ['pilotage charge', '引航费'],
    ['towage', '拖轮费'],
    ['mooring charge', '系泊费'],
    ['anchorage charge', '锚泊费'],
    ['port charge', '港口费'],
    ['port dues', '港务费'],
    ['canal toll', '运河通行费'],
    ['canal surcharge', '运河附加费'],
    ['congestion surcharge', '港口拥堵附加费'],
    ['peak season surcharge', '旺季附加费（PSS）'],
    ['high season surcharge', '旺季附加费'],
    ['low season', '淡季'],
    ['peak season', '旺季'],
    ['fuel adjustment factor', '燃油附加费（BAF/FAF）'],
    ['bunker adjustment factor', '燃油附加费（BAF）'],
    ['bunker surcharge', '燃油附加费'],
    ['currency adjustment factor', '货币贬值附加费（CAF）'],
    ['war risk surcharge', '战争险附加费'],
    ['general rate increase', '运价普涨（GRI）'],
    ['rate increase', '运价上调'],
    ['rate reduction', '运价下调'],
    ['discount', '折扣'],
    ['rebate', '回扣；运费回扣'],
    ['commission', '佣金'],
    ['agency fee', '代理费'],
    ['collect', '到付（运费到付）'],
    ['freight collect', '运费到付'],
    ['freight prepaid', '运费预付'],
    ['prepaid', '预付的'],
    ['payable at destination', '目的港付款'],
    ['cash before shipment', '装运前付款'],
    ['letter of credit', '信用证（L/C）'],
    ['sight letter of credit', '即期信用证'],
    ['usance letter of credit', '远期信用证'],
    ['irrevocable letter of credit', '不可撤销信用证'],
    ['documentary credit', '跟单信用证'],
    ['telegraphic transfer', '电汇（T/T）'],
    ['bank transfer', '银行转账'],
    ['wire transfer', '电汇'],
    ['remittance', '汇款'],
    ['advance payment', '预付款'],
    ['deposit', '押金；定金'],
    ['balance', '余额；尾款'],
    ['outstanding balance', '未付余额'],
    ['arrears', '欠款'],
    ['overdue', '逾期的'],
    ['due date', '到期日'],
    ['maturity date', '到期日'],
    ['grace period', '宽限期'],
    ['late payment charge', '滞纳金'],
    ['interest', '利息'],
    ['reimbursement', '偿付；报销'],
    ['reimburse', '偿还；报销'],
    ['settle', '结算；清偿'],
    ['settlement', '结算'],
    ['write off', '核销；注销'],
    ['write-off', '核销'],
    ['credit', '贷方；信用'],
    ['debit', '借方；借记'],
    ['bookkeeping', '记账'],
    ['double check', '复核'],
    ['invoice number', '发票号'],
    ['payment terms', '付款条件'],
    ['terms of payment', '支付条款'],
    ['currency of payment', '支付货币'],
    ['deduct', '扣除'],
    ['offset', '抵销；抵扣'],
    ['advance against documents', '凭单预付']
  ]},
  { kind: 'word', name: 'Unit 6 · 船公司/航线/船期/箱量经营', list: [
    ['shipping line', '船公司；航运公司'],
    ['ocean carrier', '海运承运人'],
    ['steamship company', '轮船公司'],
    ['alliance', '联盟'],
    ['shipping alliance', '航运联盟'],
    ['vessel sharing agreement', '舱位共享协议（VSA）'],
    ['slot charter', '舱位租赁'],
    ['slot', '舱位（箱位）'],
    ['slot allocation', '舱位分配'],
    ['capacity', '运力；装载能力'],
    ['capacity utilization', '运力利用率'],
    ['load factor', '装载率'],
    ['utilization rate', '利用率'],
    ['tonnage', '吨位'],
    ['deadweight tonnage', '载重吨（DWT）'],
    ['gross tonnage', '总吨位（GT）'],
    ['net tonnage', '净吨位（NT）'],
    ['gross registered tonnage', '总登记吨位（GRT）'],
    ['twenty-foot equivalent unit', '20英尺标准箱（TEU）'],
    ['forty-foot equivalent unit', '40英尺标准箱（FEU）'],
    ['container throughput', '集装箱吞吐量'],
    ['throughput', '吞吐量'],
    ['turnaround time', '周转时间；往返时间'],
    ['turnover', '周转量；营业额'],
    ['frequency', '班次；频率'],
    ['weekly service', '周班服务'],
    ['weekly sailing', '每周一班'],
    ['bi-weekly', '每两周一次的'],
    ['fortnightly', '每两周的'],
    ['direct service', '直达服务'],
    ['direct vessel', '直达船'],
    ['direct call', '直达挂靠'],
    ['indirect service', '中转服务'],
    ['transshipment service', '中转服务'],
    ['round voyage', '往返航次'],
    ['one-way', '单程的'],
    ['main line', '干线'],
    ['main line service', '干线服务'],
    ['feeder service', '支线服务'],
    ['feeder port', '支线港；喂给港'],
    ['hub port', '枢纽港'],
    ['transshipment port', '中转港'],
    ['port of call', '挂靠港'],
    ['calling at', '挂靠'],
    ['calling port', '挂靠港'],
    ['omit a port', '跳港；取消挂靠'],
    ['skipped port', '被跳过的港口'],
    ['port rotation', '挂港顺序'],
    ['itinerary', '航线行程'],
    ['westbound', '西行的（西向）'],
    ['eastbound', '东行的（东向）'],
    ['northbound', '北行的'],
    ['southbound', '南行的'],
    ['head haul', '去程'],
    ['back haul', '回程'],
    ['head haul cargo', '去程货'],
    ['back haul cargo', '回程货'],
    ['round trip', '往返'],
    ['transit', '过境；中转'],
    ['in transit', '在途；运输中'],
    ['transit port', '中转港；过境港'],
    ['transit time (door to door)', '门到门全程时间'],
    ['lead time', '备货期；前置时间'],
    ['turnaround', '周转'],
    ['vessel utilization', '船舶利用率'],
    ['space utilization', '舱位利用率'],
    ['shipping market', '航运市场'],
    ['spot rate', '即期运价'],
    ['long-term rate', '长约运价'],
    ['contract rate', '合同运价'],
    ['service contract', '服务合同'],
    ['volume discount', '货量折扣'],
    ['annual volume', '年货量'],
    ['minimum quantity commitment', '最低货量承诺（MQC）'],
    ['customer service', '客服'],
    ['key account', '重点客户'],
    ['sales representative', '销售代表'],
    ['marketing', '营销'],
    ['pricing', '运价制定；定价'],
    ['pricing team', '运价团队'],
    ['trade lane', '贸易航线'],
    ['trade route', '贸易航线'],
    ['lane', '航线；通道'],
    ['competition', '竞争'],
    ['competitor', '竞争对手'],
    ['market share', '市场份额'],
    ['market leader', '市场领先者'],
    ['industry', '行业'],
    ['association', '协会'],
    ['world shipping council', '世界航运理事会（WSC）'],
    ['shipping conference', '航运公会'],
    ['liner conference', '班轮公会'],
    ['conference line', '公会成员船公司'],
    ['non-conference line', '非公会船公司'],
    ['independent carrier', '独立承运人'],
    ['container operator', '集装箱经营人'],
    ['shipowner', '船东'],
    ['operator', '经营人；运营方'],
    ['charterer', '承租人'],
    ['merchant', '货方；商人'],
    ['shipping agent', '船务代理'],
    ['port agent', '港口代理'],
    ['freight forwarder', '货运代理人'],
    ['logistics', '物流'],
    ['logistics company', '物流公司'],
    ['supply chain', '供应链'],
    ['third party logistics', '第三方物流（3PL）'],
    ['warehouse', '仓库'],
    ['distribution center', '配送中心'],
    ['cross docking', '越库中转'],
    ['inventory', '库存'],
    ['outsourcing', '外包'],
    ['value-added service', '增值服务']
  ]},
  { kind: 'word', name: 'Unit 7 · 船舶类型/船体/船员/航海', list: [
    ['bulk carrier', '散货船'],
    ['container ship', '集装箱船'],
    ['container vessel', '集装箱船'],
    ['tanker', '油轮；液货船'],
    ['oil tanker', '油轮'],
    ['chemical tanker', '化学品船'],
    ['liquefied gas carrier', '液化气船'],
    ['LNG carrier', '液化天然气船'],
    ['LPG carrier', '液化石油气船'],
    ['general cargo ship', '杂货船'],
    ['multi-purpose vessel', '多用途船'],
    ['ro-ro ship', '滚装船'],
    ['ro-ro vessel', '滚装船'],
    ['car carrier', '汽车运输船'],
    ['pure car carrier', '纯汽车运输船（PCC）'],
    ['reefer ship', '冷藏船'],
    ['dry bulk carrier', '干散货船'],
    ['combined carrier', '兼用船（混装船）'],
    ['product carrier', '成品油船'],
    ['chemical carrier', '化学品船'],
    ['tugboat service', '拖轮服务'],
    ['salvage vessel', '救助船'],
    ['research vessel', '科考船'],
    ['fishing vessel', '渔船'],
    ['passenger ship', '客船'],
    ['cruise ship', '邮轮'],
    ['ferry', '渡轮'],
    ['yacht', '游艇'],
    ['cargo ship', '货船'],
    ['merchant ship', '商船'],
    ['merchant marine', '商船队'],
    ['flag', '船旗'],
    ['flag state', '船旗国'],
    ['flag of convenience', '方便旗（FOC）'],
    ['registry', '登记；船籍'],
    ['port of registry', '船籍港'],
    ['classification society', '船级社'],
    ['class', '船级'],
    ['class certificate', '船级证书'],
    ['class survey', '船级检验'],
    ['survey', '检验'],
    ['surveyor', '检验员'],
    ['hull', '船体'],
    ['bow', '船首'],
    ['stern', '船尾'],
    ['port side', '左舷'],
    ['starboard side', '右舷'],
    ['deck', '甲板'],
    ['hold', '货舱'],
    ['cargo hold', '货舱'],
    ['hatch', '舱口'],
    ['hatch cover', '舱盖'],
    ['engine room', '机舱'],
    ['bridge', '驾驶台；桥楼'],
    ['bridge deck', '驾驶台甲板'],
    ['bow thruster', '艏侧推'],
    ['propeller', '螺旋桨'],
    ['rudder', '舵'],
    ['anchor', '锚'],
    ['mast', '桅杆'],
    ['crane', '起重机；吊机'],
    ['derrick', '吊杆'],
    ['gantry crane', '龙门吊'],
    ['quay crane', '岸桥；码头起重机'],
    ['ship-to-shore crane', '岸边集装箱起重机'],
    ['spreader', '集装箱吊具'],
    ['funnel', '烟囱'],
    ['keel', '龙骨'],
    ['draft', '吃水'],
    ['draught', '吃水'],
    ['air draft', '净空高度；水上高度'],
    ['displacement', '排水量'],
    ['freeboard', '干舷'],
    ['load line', '载重线'],
    ['plimsoll line', '载重线标志'],
    ['ballast', '压载'],
    ['ballast water', '压载水'],
    ['bunker', '燃油；加燃料'],
    ['bunkering', '加燃料'],
    ['fuel oil', '燃油'],
    ['diesel oil', '柴油'],
    ['marine diesel', '船用柴油'],
    ['lubricating oil', '润滑油'],
    ['fresh water', '淡水'],
    ['crew', '船员'],
    ['captain', '船长'],
    ['master', '船长'],
    ['chief officer', '大副'],
    ['second officer', '二副'],
    ['third officer', '三副'],
    ['chief engineer', '轮机长'],
    ['chief mate', '大副'],
    ['able seaman', '一水；全能水手'],
    ['ordinary seaman', '二水；普通水手'],
    ['bosun', '水手长'],
    ['carpenter', '木匠'],
    ['cook', '厨师'],
    ['crew list', '船员名单'],
    ['seaman\'s book', '海员证'],
    ['seafarer', '海员'],
    ['seafarer\'s certificate', '海员证书'],
    ['watch', '值班'],
    ['watchkeeping', '值班'],
    ['navigation', '航行；航海'],
    ['navigate', '航行；驾驶（船舶）'],
    ['sail', '航行；启航'],
    ['set sail', '启航'],
    ['depart', '离港'],
    ['berth (v.)', '停泊；靠泊'],
    ['moor', '系泊'],
    ['cast off', '解缆'],
    ['heave up', '起锚'],
    ['drop anchor', '抛锚'],
    ['under way', '在航'],
    ['underway', '在航的'],
    ['course', '航向'],
    ['speed', '航速'],
    ['knot', '节（航速单位）'],
    ['nautical mile', '海里'],
    ['sea route', '海上航线'],
    ['charted route', '海图航线'],
    ['safe navigation', '安全航行'],
    ['collision', '碰撞'],
    ['avoid collision', '避碰'],
    ['navigation rules', '航行规则'],
    ['radar', '雷达'],
    ['echo sounder', '回声测深仪'],
    ['gyro compass', '陀螺罗经'],
    ['autopilot', '自动舵'],
    ['chart', '海图'],
    ['electronic chart', '电子海图'],
    ['buoy', '浮标'],
    ['lighthouse', '灯塔'],
    ['fairway', '航道'],
    ['channel', '航道；海峡'],
    ['shallow water', '浅水'],
    ['shoal', '浅滩'],
    ['strand', '搁浅'],
    ['run aground', '搁浅'],
    ['grounding', '搁浅'],
    ['sink', '沉没'],
    ['capsize', '倾覆'],
    ['list', '横倾'],
    ['trim', '纵倾；吃水差'],
    ['stability', '稳性'],
    ['seaworthiness', '适航性'],
    ['seaworthy', '适航的'],
    ['shipwreck', '船舶失事；沉船'],
    ['rescue', '救助；救援'],
    ['search and rescue', '搜救（SAR）'],
    ['lifeboat', '救生艇'],
    ['life raft', '救生筏'],
    ['life jacket', '救生衣'],
    ['distress', '遇险'],
    ['mayday', '遇险求救信号'],
    ['SOS', '求救信号']
  ]},
  { kind: 'word', name: 'Unit 8 · 常用缩写（带完整单词）', list: [
    ['S/O', '装货单；下货纸', 'shipping order'],
    ['B/N', '订舱单', 'booking note'],
    ['B/L', '提单', 'bill of lading'],
    ['HBL', '货代提单', 'house bill of lading'],
    ['MBL', '船东提单；主提单', 'master bill of lading'],
    ['SWB', '海运单', 'sea waybill'],
    ['OBL', '海运提单', 'ocean bill of lading'],
    ['D/O', '提货单', 'delivery order'],
    ['EIR', '集装箱设备交接单', 'equipment interchange receipt'],
    ['SI', '补料（装运指示）', 'shipping instruction'],
    ['VGM', '核实的集装箱总重', 'verified gross mass'],
    ['CFS', '集装箱货运站', 'container freight station'],
    ['CY', '集装箱堆场', 'container yard'],
    ['FCL', '整箱货', 'full container load'],
    ['LCL', '拼箱货', 'less than container load'],
    ['TEU', '20英尺标准箱', 'twenty-foot equivalent unit'],
    ['FEU', '40英尺标准箱', 'forty-foot equivalent unit'],
    ['THC', '码头操作费', 'terminal handling charge'],
    ['ORC', '启运港接货费', 'origin receiving charge'],
    ['PSS', '旺季附加费', 'peak season surcharge'],
    ['GRI', '运价普涨', 'general rate increase'],
    ['BAF', '燃油附加费', 'bunker adjustment factor'],
    ['FAF', '燃油附加费', 'fuel adjustment factor'],
    ['CAF', '货币贬值附加费', 'currency adjustment factor'],
    ['WRS', '战争险附加费', 'war risk surcharge'],
    ['D&D', '滞箱滞期费', 'demurrage and detention'],
    ['CBM', '立方米（货量）', 'cubic meter'],
    ['LOA', '总长', 'length overall'],
    ['DWT', '载重吨', 'deadweight tonnage'],
    ['GT', '总吨', 'gross tonnage'],
    ['NT', '净吨', 'net tonnage'],
    ['IMO', '国际海事组织', 'International Maritime Organization'],
    ['SOLAS', '海上人命安全公约', 'Safety of Life at Sea Convention'],
    ['MARPOL', '国际防污公约', 'International Convention for the Prevention of Pollution from Ships'],
    ['MLC', '海事劳工公约', 'Maritime Labour Convention'],
    ['ISPS', '国际船舶与港口设施保安规则', 'International Ship and Port Facility Security Code'],
    ['ISM Code', '国际安全管理规则', 'International Safety Management Code'],
    ['IMDG Code', '国际海运危险货物规则', 'International Maritime Dangerous Goods Code'],
    ['IMSBC Code', '国际海运固体散货规则', 'International Maritime Solid Bulk Cargoes Code'],
    ['PPE', '个人防护装备', 'personal protective equipment'],
    ['MSDS', '物质安全数据表', 'material safety data sheet'],
    ['SDS', '安全数据表', 'safety data sheet'],
    ['SMC', '安全管理证书', 'safety management certificate'],
    ['DOC', '符合证明（公司）', 'document of compliance'],
    ['ISSC', '国际船舶保安证书', 'international ship security certificate'],
    ['SSO', '船舶保安员', 'ship security officer'],
    ['CSO', '公司保安员', 'company security officer'],
    ['PFSO', '港口设施保安员', 'port facility security officer'],
    ['DPA', '岸上指定人员', 'designated person ashore'],
    ['PSC', '港口国监督检查', 'port state control'],
    ['FSC', '船旗国监督检查', 'flag state control'],
    ['MOU', '谅解备忘录', 'memorandum of understanding'],
    ['SOPEP', '船上油污应急计划', 'shipboard oil pollution emergency plan'],
    ['CP', '租船合同', 'charter party'],
    ['COA', '包运合同', 'contract of affreightment'],
    ['NOR', '准备就绪通知书', 'notice of readiness'],
    ['SOF', '事实记录', 'statement of facts'],
    ['COW', '原油洗舱', 'crude oil washing'],
    ['FPSO', '浮式生产储卸油装置', 'floating production storage and offloading'],
    ['STS', '船对船过驳', 'ship to ship transfer'],
    ['SPM', '单点系泊', 'single point mooring'],
    ['CALM', '悬链锚腿系泊', 'catenary anchor leg mooring'],
    ['DP', '动力定位', 'dynamic positioning'],
    ['ROV', '遥控潜水器', 'remotely operated vehicle'],
    ['AGV', '自动导引车', 'automated guided vehicle'],
    ['RTG', '轮胎式龙门吊', 'rubber tyred gantry crane'],
    ['RMG', '轨道式龙门吊', 'rail mounted gantry crane'],
    ['ASC', '自动化堆场吊', 'automated stacking crane'],
    ['POD', '交货证明', 'proof of delivery'],
    ['GRN', '收货单', 'goods received note'],
    ['PO', '采购订单', 'purchase order'],
    ['RFQ', '询价（请求报价）', 'request for quotation'],
    ['RFP', '方案征询', 'request for proposal'],
    ['NDA', '保密协议', 'non-disclosure agreement'],
    ['LOI', '保函', 'letter of indemnity'],
    ['POA', '授权委托书', 'power of attorney'],
    ['CO', '原产地证书', 'certificate of origin'],
    ['CIQ', '出入境检验检疫', 'China Entry-Exit Inspection and Quarantine'],
    ['AEO', '经认证的经营者', 'authorized economic operator'],
    ['HTS', '美国协调关税税则', 'Harmonized Tariff Schedule'],
    ['VAT', '增值税', 'value added tax'],
    ['T/T', '电汇', 'telegraphic transfer'],
    ['L/C', '信用证', 'letter of credit'],
    ['D/P', '付款交单', 'documents against payment'],
    ['D/A', '承兑交单', 'documents against acceptance'],
    ['EDI', '电子数据交换', 'electronic data interchange'],
    ['PCS', '港口信息平台', 'port community system'],
    ['TOS', '码头操作系统', 'terminal operating system'],
    ['WMS', '仓库管理系统', 'warehouse management system'],
    ['TMS', '运输管理系统', 'transport management system'],
    ['KPI', '关键绩效指标', 'key performance indicator'],
    ['ROI', '投资回报率', 'return on investment'],
    ['TCE', '期租等价（收益）', 'time charter equivalent'],
    ['BDI', '波罗的海干散货运价指数', 'Baltic Dry Index'],
    ['SCFI', '上海出口集装箱运价指数', 'Shanghai Containerized Freight Index'],
    ['CCFI', '中国出口集装箱运价指数', 'China Containerized Freight Index'],
    ['FFA', '远期运费协议', 'forward freight agreement'],
    ['EEDI', '能效设计指数', 'energy efficiency design index'],
    ['EEXI', '现有船能效指数', 'energy efficiency existing ship index'],
    ['CII', '碳强度指标', 'carbon intensity indicator'],
    ['ECA', '排放控制区', 'emission control area'],
    ['VLSFO', '极低硫燃油', 'very low sulphur fuel oil'],
    ['MGO', '船用轻柴油', 'marine gas oil'],
    ['LNG', '液化天然气', 'liquefied natural gas'],
    ['LPG', '液化石油气', 'liquefied petroleum gas'],
    ['OSV', '平台供应船', 'offshore supply vessel'],
    ['AHTS', '三用工作船', 'anchor handling tug supply vessel'],
    ['SOV', '风电运维船', 'service operation vessel'],
    ['PCC', '纯汽车运输船', 'pure car carrier'],
    ['RO-RO', '滚装船', 'roll-on/roll-off'],
    ['LO-LO', '吊装（吊上吊下）', 'lift-on/lift-off'],
    ['FLO-FLO', '浮装式', 'float-on/float-off'],
    ['OOG', '超限货', 'out of gauge'],
    ['W/M', '重量或尺码计费', 'weight or measurement'],
    ['ASAP', '尽快', 'as soon as possible'],
    ['TBA', '待通知', 'to be advised'],
    ['TBC', '待确认', 'to be confirmed'],
    ['TBD', '待定', 'to be determined'],
    ['N/A', '不适用', 'not applicable'],
    ['P/L', '装箱单', 'packing list'],
    ['I/V', '商业发票', 'invoice'],
    ['C/N', '贷项通知单', 'credit note'],
    ['D/N', '借项通知单', 'debit note'],
    ['A/N', '到货通知', 'arrival notice'],
    ['HAWB', '分运单（空运）', 'house air waybill'],
    ['MAWB', '主运单（空运）', 'master air waybill'],
    ['AWB', '空运单', 'air waybill'],
    ['UPS', '不间断电源', 'uninterruptible power supply'],
    ['CFS/CY', '站到场（拼箱交接）', 'container freight station to container yard'],
    ['CY/CY', '场到场（整箱交接）', 'container yard to container yard']
  ]},
  { kind: 'word', name: 'Unit 9 · 租船/合同/贸易术语（缩写含全称）', list: [
    ["FOB","船上交货","free on board"],
    ["FCA","货交承运人","free carrier"],
    ["FAS","船边交货","free alongside ship"],
    ["EXW","工厂交货","ex works"],
    ["CFR","成本加运费","cost and freight"],
    ["CIF","成本保险费加运费","cost insurance and freight"],
    ["CPT","运费付至","carriage paid to"],
    ["CIP","运费保险费付至","carriage and insurance paid to"],
    ["DAP","目的地交货","delivered at place"],
    ["DPU","卸货地交货","delivered at place unloaded"],
    ["DDP","完税后交货","delivered duty paid"],
    ["time charter","期租"],
    ["voyage charter","航次租船"],
    ["bareboat charter","光船租赁"],
    ["demise charter","光船租赁（转让占有）"],
    ["charter hire","租金"],
    ["hire payment","支付租金"],
    ["off-hire","停租"],
    ["on-hire","起租"],
    ["redelivery","还船"],
    ["delivery of the vessel","交船"],
    ["laycan","受载期/解约期"],
    ["cancelling date","解约日"],
    ["whether in berth or not","不论是否靠泊"],
    ["whether in port or not","不论是否在港"],
    ["whether in free pratique or not","不论是否获得检疫放行"],
    ["despatch money","速遣费"],
    ["reversible laytime","可调剂装卸时间"],
    ["weather working day","晴天工作日"],
    ["trip time charter","航次期租"],
    ["gencon","金康租船合同格式"],
    ["NYPE","纽约土产格式","New York Produce Exchange Form"],
    ["fixture note","成交确认书"],
    ["recap","成交确认摘要"],
    ["free pratique","检疫放行"],
    ["bill of exchange","汇票"],
    ["documentary collection","跟单托收"],
    ["performance bond","履约保函"],
    ["advance payment bond","预付款保函"],
    ["bank guarantee","银行保函"],
    ["side letter","附函"],
    ["general average","共同海损"],
    ["particular average","单独海损"],
    ["salvage","救助；救助报酬"],
    ["sue and labour","施救费用"],
    ["limitation of liability","责任限制"],
    ["himalaya clause","喜马拉雅条款"],
    ["paramount clause","首要条款"],
    ["both to blame collision clause","双方有责碰撞条款"],
    ["new jason clause","新杰森条款"],
    ["cesser clause","责任终止条款"],
    ["lien","留置权"],
    ["demise clause","光船条款"],
    ["identity of carrier clause","承运人识别条款"],
    ["voyage policy","航次保险单"],
    ["time policy","定期保险单"],
    ["floating policy","流动保险单"],
    ["open cover","预约保险"],
    ["warehouse to warehouse clause","仓至仓条款"],
    ["all risks","一切险"],
    ["with average","水渍险"],
    ["FPA","平安险","free from particular average"],
    ["institute cargo clauses","协会货物条款"],
    ["P&I","保赔险","protection and indemnity"],
    ["war risk","战争险"],
    ["strike risk","罢工险"],
    ["port of refuge","避难港"],
    ["general average adjustment","共同海损理算"],
    ["salvage charges","救助费用"],
    ["average adjuster","海损理算师"],
    ["adjustment of general average","共同海损理算"],
    ["declaration of general average","共同海损宣布"],
    ["general average deposit","共同海损保证金"],
    ["general average security","共同海损担保"],
    ["no cure no pay","无效果无报酬"],
    ["sister ship","姐妹船"],
    ["associated ship","关联船舶"],
    ["arrest of vessel","扣押船舶"],
    ["maritime lien","船舶优先权"],
    ["admiralty court","海事法院"],
    ["jurisdiction","管辖权"],
    ["governing law","管辖法律"],
    ["arbitration","仲裁"],
    ["arbitration clause","仲裁条款"],
    ["arbitral award","仲裁裁决"],
    ["enforcement of award","裁决执行"],
    ["security for costs","诉讼费用担保"],
    ["letter of undertaking","保函"],
    ["club letter of undertaking","保赔协会保函"],
    ["right of subrogation","代位求偿权"],
    ["counter-security","反担保"],
    ["anchorage dues","锚泊费"],
    ["canal dues","运河费"],
    ["suez canal transit","苏伊士运河过境"],
    ["tonnage dues","吨税"],
    ["free alongside","船边交货"],
    ["free in","船东不负责装货费（FI）"],
    ["free out","船东不负责卸货费（FO）"],
    ["free in and out","船东不负责装卸费（FIO）"],
    ["gross terms","船东负责装卸费"],
    ["liner terms","班轮条款"],
    ["hook to hook","钩到钩"],
    ["tackle to tackle","吊钩到吊钩"],
    ["rail to rail","船舷到船舷"],
  ]},
  { kind: 'word', name: 'Unit 10 · 保险/索赔/安全/港口国/法规补充', list: [
    ["insurable interest","可保利益"],
    ["insurable value","可保价值"],
    ["insured amount","保险金额"],
    ["sum insured","保险金额"],
    ["policy holder","投保人；保单持有人"],
    ["named insured","记名被保险人"],
    ["additional insured","附加被保险人"],
    ["loss payee","损失受益人"],
    ["premium rate","保险费率"],
    ["additional premium","附加保费"],
    ["return premium","退保费"],
    ["pro rata premium","按比例保费"],
    ["minimum premium","最低保费"],
    ["net premium","净保费"],
    ["gross premium","毛保费"],
    ["deductible","免赔额"],
    ["franchise","相对免赔额"],
    ["excess clause","免赔额条款"],
    ["average clause","海损条款"],
    ["special conditions","特别条款（保险）"],
    ["general conditions","一般条款（保险）"],
    ["marine insurance act","海上保险法"],
    ["utmost good faith","最大诚信原则"],
    ["proximate cause","近因"],
    ["indemnity principle","补偿原则"],
    ["subrogation","代位求偿"],
    ["abandonment","委付"],
    ["constructive total loss","推定全损"],
    ["actual total loss","实际全损"],
    ["total loss of part","部分全损"],
    ["loss of use","使用损失"],
    ["consequential loss","间接损失"],
    ["loss of profit","利润损失"],
    ["damage survey","货损检验"],
    ["claim survey","理赔检验"],
    ["loss adjuster","损失理算人"],
    ["claims department","理赔部门"],
    ["notice of loss","损失通知"],
    ["claims documents","索赔单证"],
    ["proof of loss","损失证明"],
    ["survey report","检验报告"],
    ["damage report","货损报告"],
    ["shortage report","短量报告"],
    ["tally report","理货报告"],
    ["exception list","异常清单"],
    ["cargo worthiness","适货性"],
    ["proper and careful loading","妥善谨慎装货"],
    ["due diligence","克尽职责"],
    ["period of responsibility","责任期间"],
    ["port to port","港到港"],
    ["door to door","门到门"],
    ["container yard to door","场到门"],
    ["door to container yard","门到场"],
    ["port state control officer","港口国检查官"],
    ["deficiency","缺陷（检查）"],
    ["rectify deficiency","纠正缺陷"],
    ["follow-up inspection","跟踪复查"],
    ["expanded inspection","扩大检查"],
    ["target factor","检查选船因素"],
    ["ship risk profile","船舶风险画像"],
    ["clear grounds","明显依据"],
    ["substandard ship","低标准船"],
    ["flag administration","船旗国主管机关"],
    ["recognized organization","被认可组织"],
    ["statutory survey","法定检验"],
    ["renewal survey","换证检验"],
    ["annual survey","年度检验"],
    ["intermediate survey","中期检验"],
    ["special survey","特别检验"],
    ["bottom survey","船底检验"],
    ["tailshaft survey","尾轴检验"],
    ["in-water survey","水下检验"],
    ["continuous survey","循环检验"],
    ["survey status","检验状态"],
    ["outstanding recommendations","未完成建议"],
    ["class maintained","船级保持"],
    ["class suspended","船级暂停"],
    ["class withdrawn","船级撤销"],
    ["certificate renewal","证书换新"],
    ["expired certificate","过期证书"],
    ["provisional certificate","临时证书"],
    ["exemption certificate","免除证书"],
    ["endorsement of certificate","证书签注"],
    ["statutory certificates on board","船上法定证书"],
    ["seafarer employment agreement","海员就业协议"],
    ["certificate of competency","适任证书"],
    ["medical certificate","健康证明"],
    ["fitness certificate","健康适任证书"],
    ["minimum safe manning","最低安全配员"],
    ["manning certificate","配员证书"],
    ["shore leave","船员上岸"],
    ["repatriation","遣返"],
    ["crew change","船员换班"],
    ["sign on","上船"],
    ["sign off","下船"],
    ["piracy","海盗行为"],
    ["armed robbery","武装抢劫"],
    ["security level","保安等级"],
    ["security incident","保安事件"],
    ["security drill","保安演习"],
    ["contraband","违禁品"],
    ["smuggling","走私"],
    ["drugs","毒品"],
    ["illegal cargo","非法货物"],
    ["shipping safety","航运安全"],
    ["safety culture","安全文化"],
    ["near miss","险情（未遂事故）"],
    ["accident reporting","事故报告"],
    ["incident investigation","事件调查"],
    ["root cause analysis","根本原因分析"],
    ["corrective action","纠正措施"],
    ["preventive action","预防措施"],
    ["lessons learned","经验教训"],
    ["safety management system","安全管理体系"],
    ["internal audit","内部审核"],
    ["external audit","外部审核"],
    ["management review","管理评审"],
    ["non-conformity","不符合项"],
    ["observation","观察项（审核）"],
    ["company safety officer","公司安全员"],
    ["vessel safety officer","船舶安全员"],
    ["safety meeting","安全会议"],
    ["tool box meeting","班前会"],
    ["pre-work briefing","作业前交底"],
    ["job safety analysis","作业安全分析"],
    ["permit to work","作业许可"],
    ["hot work permit","动火许可"],
    ["confined space entry","密闭舱室进入"],
    ["enclosed space entry","封闭舱室进入"],
    ["gas test","气体检测"],
    ["oxygen deficiency","缺氧"],
    ["explosive atmosphere","爆炸性环境"],
    ["entry supervisor","进入监护人"],
    ["standby man","舱口监护"],
    ["rescue equipment","救援设备"],
    ["escape route","逃生路线"],
    ["emergency muster","应急集合"],
    ["abandon ship","弃船"],
    ["man overboard","人员落水"],
    ["fire fighting","消防"],
    ["fire drill","消防演习"],
    ["emergency response plan","应急响应计划"],
    ["contingency plan","应急计划"],
    ["drill record","演习记录"],
    ["training record","培训记录"],
    ["certificate of training","培训证书"],
    ["familiarization","熟悉培训"],
    ["induction training","入职培训"],
    ["refresher training","复训"],
    ["drill and exercise","演练"],
    ["emergency preparedness","应急准备"],
    ["pollution prevention","防污染"],
    ["garbage management plan","垃圾管理计划"],
    ["garbage record book","垃圾记录簿"],
    ["oil record book","油类记录簿"],
    ["cargo record book","货物记录簿"],
    ["ballast water management plan","压载水管理计划"],
    ["ballast water record book","压载水记录簿"],
    ["bunkering operation","加油作业"],
    ["oil transfer operation","过驳作业"],
    ["spill response","溢油应急"],
    ["dispersant","消油剂"],
    ["containment boom","围油栏"],
    ["absorbent material","吸油材料"],
    ["shore reception facility","岸上接收设施"],
    ["waste discharge","废物排放"],
    ["sewage treatment","污水处理"],
    ["incinerator","焚烧炉"],
    ["garbage disposal","垃圾处理"],
    ["emission reduction","减排"],
    ["carbon footprint","碳足迹"],
    ["greenhouse gas","温室气体"],
    ["energy efficiency","能效"],
    ["shore power","岸电"],
    ["alternative fuel","替代燃料"],
  ]},
  { kind: 'phrase', name: "短语 Unit 1 · 邮件开头/客套/致谢/结尾", list: [
    ["Dear Sir or Madam,","尊敬的先生/女士（邮件开头）"],
    ["Dear Mr. / Ms. [name],","尊敬的[姓名]先生/女士"],
    ["To whom it may concern,","敬启者（致相关人士）"],
    ["Good morning / afternoon,","上午好/下午好"],
    ["I hope this email finds you well.","希望您一切安好（客套开头）"],
    ["Hope all is well with you.","希望您一切顺利"],
    ["Thank you for your email.","感谢您的来信"],
    ["Thank you for your prompt reply.","感谢您的及时回复"],
    ["Thanks for getting back to me.","感谢您的回复"],
    ["We refer to your email dated...","关于贵方…日期的邮件"],
    ["Further to our previous email,","继我们上一封邮件之后"],
    ["With reference to our conversation,","关于我们的沟通"],
    ["I am writing to inform you that...","特此函告……"],
    ["I am writing to confirm that...","特此确认……"],
    ["I am writing to request...","特此请求……"],
    ["We would like to draw your attention to...","我们想提请贵方注意……"],
    ["Please be advised that...","特此通知……"],
    ["Please note that...","请注意……"],
    ["This is to confirm that...","此函确认……"],
    ["We are pleased to inform you that...","我们很高兴地通知您……"],
    ["We are sorry to inform you that...","很遗憾地通知您……"],
    ["We regret to advise that...","我们很遗憾地告知……"],
    ["We are writing to update you on...","特此向您通报……的最新进展"],
    ["We would like to bring to your attention...","我们想提请贵方关注……"],
    ["Please find attached...","随附……请查收"],
    ["Attached please find...","随函附上……"],
    ["Please see the attachment for details.","详见附件"],
    ["Kindly find enclosed...","随函附上……"],
    ["Enclosed are the documents for your reference.","随附文件供您参考"],
    ["Please review the attached documents.","请审阅附件文件"],
    ["We have attached... for your perusal.","我们随附……供您阅览"],
    ["As requested, please find...","按要求随附……"],
    ["Per your request, we have arranged...","按您的要求，我们已安排……"],
    ["In accordance with your instructions,","遵照您的指示"],
    ["As per our agreement,","按照我们的约定"],
    ["As discussed, we confirm...","如所讨论，我们确认……"],
    ["Following our telephone conversation,","继我们的电话沟通之后"],
    ["Could you please...?","您能否……？"],
    ["Would you please...?","请您……好吗？"],
    ["Please kindly...","请您（客气请求）"],
    ["We would appreciate it if you could...","如果您能……我们将不胜感激"],
    ["It would be greatly appreciated if...","如……将不胜感激"],
    ["Please let us know your comments.","请告知您的意见"],
    ["Please do not hesitate to contact us.","请随时与我们联系"],
    ["Should you have any questions, please let us know.","如有任何问题请告知我们"],
    ["If you need any further information, please contact us.","如需更多信息请联系我们"],
    ["We look forward to hearing from you.","期待您的回复"],
    ["We look forward to your reply.","期待您的答复"],
    ["We look forward to working with you.","期待与您合作"],
    ["We look forward to your confirmation.","期待您的确认"],
    ["We await your reply.","静候您的回复"],
    ["We await your instructions.","等待您的指示"],
    ["Your early reply will be appreciated.","如能早日回复将不胜感激"],
    ["Thank you for your cooperation.","感谢您的配合"],
    ["Thank you for your understanding.","感谢您的理解"],
    ["Thank you for your patience.","感谢您的耐心"],
    ["We apologize for any inconvenience caused.","对造成的不便深表歉意"],
    ["We apologize for the delay.","对延误深表歉意"],
    ["Please accept our apologies.","请接受我们的歉意"],
    ["Best regards,","此致敬意（邮件结尾）"],
    ["Kind regards,","此致敬意（邮件结尾）"],
    ["Yours sincerely,","谨上（邮件结尾）"],
    ["With kind regards,","致以亲切的问候"],
    ["Thanks and best regards,","感谢并致敬"],
  ]},
  { kind: 'phrase', name: "短语 Unit 2 · 订舱/船期/安排/通知", list: [
    ["We would like to book space on the vessel...","我们想订……船（名/航次）的舱位"],
    ["Please arrange booking for the following cargo.","请为以下货物安排订舱"],
    ["Kindly book 1x40HQ for shipment...","请订1个40尺高箱，装运……"],
    ["We request space on the next available sailing.","我们请求下一班船的舱位"],
    ["Please advise the sailing schedule.","请告知船期"],
    ["Please confirm the vessel name and voyage number.","请确认船名和航次号"],
    ["Please advise the cut-off time.","请告知截关/截单时间"],
    ["What is the closing time for this vessel?","这班船的截关时间是什么时候？"],
    ["Please confirm whether space is available.","请确认是否有舱位"],
    ["We would like to change the vessel for this shipment.","我们想为这批货改配船"],
    ["Please roll this cargo to the next vessel.","请把这批货甩到下一班船"],
    ["Please cancel the booking for...","请取消……的订舱"],
    ["We need to move the cargo to the next sailing.","我们需要把货延到下一航次"],
    ["Please re-book the cargo on the next available vessel.","请把货物改订到下一班可用船"],
    ["Kindly advise the ETA of the vessel.","请告知船舶预计到港时间"],
    ["Please confirm the ETD of the vessel.","请确认船舶预计离港时间"],
    ["We will advise the vessel schedule once confirmed.","船期确认后我们会通知您"],
    ["Please arrange transshipment at...","请在……安排转运"],
    ["The cargo will be transshipped at...","货物将在……转运"],
    ["Please advise the transshipment port.","请告知转运港"],
    ["Please ensure the cargo is ready for loading.","请确保货物备妥待装"],
    ["The cargo must be ready by...","货物必须在……前备妥"],
    ["Please arrange the truck for pickup.","请安排拖车提货"],
    ["We will arrange the delivery by truck.","我们将安排卡车送货"],
    ["Please arrange container pickup at the depot.","请在堆场安排提箱"],
    ["Please return the empty container to...","请把空箱还到……"],
    ["Please arrange the delivery of the empty container.","请安排送空箱"],
    ["Please confirm the delivery address.","请确认交货地址"],
    ["Please advise the pickup location.","请告知提货地点"],
    ["Please arrange customs clearance.","请安排清关"],
    ["Please proceed with customs clearance for this shipment.","请为本票货办理清关"],
    ["We will arrange customs declaration.","我们将安排报关"],
    ["Please advise if the cargo has been cleared.","请告知货物是否已清关"],
    ["The cargo is under customs inspection.","货物正在接受海关查验"],
    ["Please inform us when the cargo is released.","货物放行后请通知我们"],
    ["Please arrange the loading operation.","请安排装货作业"],
    ["The vessel is now loading.","船舶正在装货"],
    ["Please advise the loading progress.","请告知装货进度"],
    ["Loading is expected to complete on...","预计……完成装货"],
    ["Please arrange the discharge operation.","请安排卸货作业"],
    ["The vessel is expected to arrive on...","船舶预计……到港"],
    ["Please confirm the berthing time.","请确认靠泊时间"],
    ["Please advise the expected time of berthing.","请告知预计靠泊时间"],
    ["We will advise once the vessel is berthed.","船舶靠泊后我们会通知您"],
    ["Please arrange the surveyor.","请安排检验员"],
    ["Please arrange an inspection before loading.","请安排装货前检验"],
    ["Please arrange a joint survey.","请安排联合检验"],
    ["The survey will be carried out at...","检验将在……进行"],
    ["Please arrange the tallying service.","请安排理货服务"],
    ["Please send us the tally report.","请把理货报告发给我们"],
    ["Please advise the actual loaded quantity.","请告知实际装货数量"],
    ["Please confirm the quantity discharged.","请确认卸货数量"],
    ["There is a shortage of...","……有短少"],
    ["The cargo is over-carried to...","货物被错运到……"],
    ["Please arrange to return the over-carried cargo.","请安排把错运货物运回"],
    ["Please arrange the re-shipment.","请安排重新装运"],
    ["The cargo will be sent to the next port.","货物将运往下一港"],
    ["Please arrange the delivery against the original B/L.","请凭正本提单安排放货"],
    ["Please arrange telex release.","请安排电放"],
    ["We confirm telex release for this shipment.","我们确认本票货电放"],
    ["Please release the cargo against the telex release.","请凭电放放货"],
    ["Please advise the release arrangement.","请告知放货安排"],
    ["The original B/L will be surrendered at...","正本提单将在……交回"],
  ]},
  { kind: 'phrase', name: "短语 Unit 3 · 费用/付款/发票/催款", list: [
    ["Please find the freight invoice attached.","随附运费发票请查收"],
    ["We enclose our debit note for the freight charge.","随附运费借项通知单"],
    ["The total charge amounts to USD...","总费用为……美元"],
    ["Please find the cost breakdown as follows.","费用明细如下"],
    ["The charges are as follows:","费用如下："],
    ["Freight is payable at destination.","运费到付"],
    ["Freight is prepaid.","运费预付"],
    ["All charges are prepaid.","所有费用预付"],
    ["The freight will be collected at destination.","运费将在目的港收取"],
    ["Please arrange payment by T/T.","请安排电汇付款"],
    ["Payment should be made within 30 days.","应在30天内付款"],
    ["Please settle the outstanding amount of...","请结清……未付金额"],
    ["The balance of USD... is still outstanding.","仍有……美元尾款未付"],
    ["According to our records, the payment is overdue.","根据我方记录，该款项已逾期"],
    ["May we remind you that the invoice is due on...?","提醒您发票于……到期"],
    ["Kindly arrange settlement at your earliest convenience.","请尽早安排结款"],
    ["We would appreciate prompt payment.","恳请尽快付款"],
    ["Please note that a late payment charge will apply.","请注意将产生滞纳金"],
    ["We have received your payment. Thank you.","已收到您的付款，谢谢"],
    ["Your payment has been applied to invoice no....","您的付款已核销到发票号……"],
    ["Please confirm receipt of our payment.","请确认收到我们的付款"],
    ["We will issue the receipt upon payment.","收款后我们将开具收据"],
    ["Please provide a receipt for the payment made.","请提供付款收据"],
    ["Please send us the bank transfer slip.","请把银行转账回单发给我们"],
    ["Please indicate the invoice number in your payment.","付款时请注明发票号"],
    ["The payment has been made by T/T.","款项已通过电汇支付"],
    ["Please note the remittance details.","请注意汇款信息"],
    ["Our bank details are as follows:","我方银行信息如下："],
    ["Please arrange payment to the following account.","请汇入以下账户"],
    ["The exchange rate applied is...","适用的汇率为……"],
    ["Please confirm the total amount before payment.","付款前请确认总金额"],
    ["Please check the invoice amount.","请核对发票金额"],
    ["There seems to be a discrepancy in the invoice.","发票金额似乎有不一致"],
    ["Please issue a revised invoice.","请重新出具发票"],
    ["We will issue a credit note for the difference.","差额我们将出具贷项通知单"],
    ["Please issue a debit note for the extra charge.","额外费用我们将出具借项通知单"],
    ["The surcharge is not included in the quoted rate.","附加费未包含在报价中"],
    ["The rate quoted is subject to the surcharges.","所报运价另加附加费"],
    ["Please advise the current surcharges.","请告知当前的附加费"],
    ["Please confirm the rate is valid until...","请确认该运价有效期至……"],
    ["The quotation is valid for 7 days.","报价有效期7天"],
    ["Please note the rates are subject to change.","请注意运价可能调整"],
    ["We will revert with our best rate.","我们会尽快给您最优运价"],
    ["Please find our revised quotation attached.","随附修改后的报价请查收"],
    ["Could you please review the rate and advise?","请您复核运价并告知"],
    ["We hope you can offer a more competitive rate.","希望您能提供更有竞争力的运价"],
    ["Given the volume, we request a special rate.","鉴于货量，我们请求优惠运价"],
    ["We can offer a discount for large volumes.","货量大可给予折扣"],
    ["The price includes all charges except...","价格含所有费用，除……外"],
    ["The price is exclusive of tax.","价格不含税"],
    ["The price is inclusive of all local charges.","价格含所有当地费用"],
    ["Local charges at destination are for the account of consignee.","目的港当地费用由收货人承担"],
    ["The origin charges are for the shipper's account.","起运港费用由托运人承担"],
    ["All charges are for the account of the merchant.","所有费用由货方承担"],
    ["The terminal handling charge is for the account of the consignee.","码头操作费由收货人承担"],
    ["Please advise who will bear the detention charge.","请告知滞箱费由谁承担"],
    ["The demurrage charge will be billed to you.","滞期费将向您收取"],
    ["Please note the free time expires on...","请注意免费期于……到期"],
    ["We will start to charge storage from...","从……起开始计收堆存费"],
    ["Please arrange payment of the storage charge.","请安排支付堆存费"],
    ["The charge has been waived this time.","本次费用已免除"],
    ["No charge will be made for this service.","此项服务不收费"],
    ["Please claim the refund from the insurance company.","请向保险公司索赔退款"],
  ]},
  { kind: 'phrase', name: "短语 Unit 4 · 单证/文件/报关/补料", list: [
    ["Please provide the shipping instructions (SI).","请提供补料（装运指示）"],
    ["Kindly submit the SI before the cut-off time.","请在截止时间前提交补料"],
    ["Please send us the draft B/L for checking.","请把提单草稿发给我们核对"],
    ["Please check the draft bill of lading and revert.","请核对提单草稿并回复"],
    ["Please confirm the B/L details.","请确认提单信息"],
    ["We confirm the B/L contents are correct.","我们确认提单内容无误"],
    ["Please amend the B/L as follows.","请按如下修改提单"],
    ["Please issue the original bill of lading.","请签发正本提单"],
    ["Please issue three original B/Ls.","请签发三份正本提单"],
    ["How many original bills of lading are required?","需要几份正本提单？"],
    ["Please prepare a full set of original B/Ls.","请准备全套正本提单"],
    ["Please issue the telex release.","请办理电放"],
    ["We request telex release for this shipment.","本票货我们申请电放"],
    ["Please surrender the original B/L for telex release.","请交回正本提单以办理电放"],
    ["Please confirm the consignee and notify party.","请确认收货人和通知方"],
    ["Please provide the full address of the consignee.","请提供收货人完整地址"],
    ["Please provide the shipper's full name and address.","请提供托运人全称和地址"],
    ["Please advise the HS code of the cargo.","请告知货物HS编码"],
    ["Please provide the cargo description in detail.","请提供详细的货物描述"],
    ["The cargo description must be accurate.","货物描述必须准确"],
    ["Please provide the marks and numbers.","请提供唛头"],
    ["Please advise the gross weight and measurement.","请告知毛重和尺码"],
    ["Please provide the container number and seal number.","请提供箱号和封号"],
    ["Please confirm the container number.","请确认箱号"],
    ["Please advise the total number of packages.","请告知总件数"],
    ["Please confirm the quantity loaded.","请确认装货数量"],
    ["Please advise the weight per container.","请告知每个集装箱的重量"],
    ["Please provide the VGM declaration.","请提供VGM申报"],
    ["The VGM must be submitted before loading.","VGM须在装货前提交"],
    ["Please provide the shipping marks.","请提供唛头"],
    ["Please prepare the commercial invoice.","请准备商业发票"],
    ["Please provide the packing list.","请提供装箱单"],
    ["Please send us the customs declaration form.","请把报关单发给我们"],
    ["Please provide the certificate of origin.","请提供原产地证书"],
    ["Please provide the inspection certificate.","请提供检验证书"],
    ["Please provide the fumigation certificate.","请提供熏蒸证书"],
    ["Please provide the insurance certificate.","请提供保险凭证"],
    ["Please prepare the customs clearance documents.","请准备清关文件"],
    ["The documents are required for customs clearance.","清关需要这些文件"],
    ["Please send all documents by email.","请把所有文件用邮件发送"],
    ["Please send the original documents by courier.","请把正本文件快递寄出"],
    ["The originals will be sent by courier.","正本将快递寄出"],
    ["We will courier the documents to you.","我们会把文件快递给您"],
    ["Please acknowledge receipt of the documents.","请确认收到文件"],
    ["We have received the documents. Thank you.","文件已收到，谢谢"],
    ["Please find the documents attached for your reference.","随附文件供您参考"],
    ["Please sign and return the document.","请签署后寄回该文件"],
    ["Please stamp and return the copy.","请盖章后退回副本"],
    ["Please provide a copy of the B/L for our file.","请提供一份提单副本存档"],
    ["Please note the B/L number.","请注意提单号"],
    ["The B/L number is...","提单号为……"],
    ["Please note that the container seal was found broken.","请注意发现箱封破损"],
    ["We found a discrepancy between the documents and the cargo.","我们发现单货不符"],
    ["Please correct the data and resubmit.","请更正数据后重新提交"],
    ["Please advise if any amendment is required.","如需修改请告知"],
    ["The amendment fee will apply.","将收取改单费"],
    ["Please note that the documents have been amended.","请注意单证已修改"],
    ["Please confirm whether the goods can be released.","请确认货物是否可以放行"],
    ["The cargo is now released by customs.","货物现已海关放行"],
    ["Please advise the delivery arrangement for the cargo.","请告知货物的放货安排"],
    ["Please arrange the issuance of the delivery order.","请安排出具提货单"],
  ]},
  { kind: 'phrase', name: '短语 Unit 5 · 异常/延误/索赔/道歉/跟进', list: [
    ["We regret to inform you that the vessel is delayed.","很遗憾通知您船舶延误了"],
    ["The vessel will be delayed by approximately...","船舶将延误约……"],
    ["The vessel is now expected to arrive on...","船舶现预计……到港"],
    ["Please note the revised schedule.","请注意修改后的船期"],
    ["The schedule has changed as follows:","船期变更如下："],
    ["We apologize for the delay caused by...","对因……造成的延误深表歉意"],
    ["The delay was caused by bad weather.","延误由恶劣天气造成"],
    ["The delay was caused by port congestion.","延误由港口拥堵造成"],
    ["We are doing our best to minimize the delay.","我们正尽力减少延误"],
    ["We will keep you informed of any further changes.","如有进一步变化我们会通知您"],
    ["Please accept our apologies for the late delivery.","对延迟交货深表歉意"],
    ["The delivery will be postponed to...","交货将推迟到……"],
    ["We apologize for the inconvenience caused.","对造成的不便深表歉意"],
    ["We understand the impact on your schedule.","我们理解这对您船期的影响"],
    ["We will revert once we have more information.","有进一步消息我们会再通知您"],
    ["Please note that the shipment has been delayed.","请注意本票货已延误"],
    ["The cargo will be shipped on the next vessel.","货物将装下一班船"],
    ["We are arranging an alternative vessel.","我们正在安排替代船舶"],
    ["Please advise whether you agree to the alternative arrangement.","请告知是否同意替代安排"],
    ["We apologize for any inconvenience this may cause.","对此可能造成的不便深表歉意"],
    ["We found damage to the cargo upon discharge.","卸货时发现货物受损"],
    ["The container was found damaged on arrival.","到货时发现集装箱受损"],
    ["We have noted the shortage of...","我们已记录……短少"],
    ["A survey has been arranged.","已安排检验"],
    ["Please arrange a survey within 24 hours.","请在24小时内安排检验"],
    ["Please keep the damaged goods for inspection.","请保留受损货物以供检验"],
    ["Do not dispose of the damaged cargo before inspection.","检验前请勿处置受损货物"],
    ["Please take photos of the damage as evidence.","请拍照留作货损证据"],
    ["Please provide the survey report.","请提供检验报告"],
    ["We will claim against the carrier for the damage.","我们将就货损向承运人索赔"],
    ["We would like to lodge a claim for the loss.","我们想就损失提出索赔"],
    ["Please provide the supporting documents for the claim.","请提供索赔证明文件"],
    ["The claim documents are as follows:","索赔文件如下："],
    ["Please note the claim should be filed within...","请注意索赔应在……内提出"],
    ["We are processing your claim.","我们正在处理您的索赔"],
    ["Your claim has been accepted.","您的索赔已被接受"],
    ["Your claim has been rejected.","您的索赔已被拒绝"],
    ["We will compensate you for the loss.","我们将赔偿您的损失"],
    ["The compensation will be settled by...","赔偿将于……结清"],
    ["Please confirm the amount of compensation.","请确认赔偿金额"],
    ["We have received your claim. We will revert shortly.","已收到您的索赔，将尽快回复"],
    ["We are investigating the matter.","我们正在调查此事"],
    ["We will look into the matter and get back to you.","我们会调查此事并回复您"],
    ["Please give us some time to check.","请给我们一些时间核实"],
    ["We will come back to you with an update.","我们会向您通报进展"],
    ["The matter is under investigation.","此事正在调查中"],
    ["We will update you once the investigation is completed.","调查结束后我们会通知您"],
    ["We apologize for the error.","对错误深表歉意"],
    ["The error was due to a clerical mistake.","错误系笔误/录入错误所致"],
    ["We have corrected the mistake.","我们已更正错误"],
    ["Please find the corrected document attached.","随附更正后的文件"],
    ["We will take measures to prevent recurrence.","我们将采取措施防止再次发生"],
    ["We assure you that this will not happen again.","我们保证不会再发生"],
    ["Please accept our sincere apologies.","请接受我们诚挚的歉意"],
    ["We value your business and apologize for the trouble.","我们珍视与您的合作，对造成的麻烦致歉"],
    ["We will follow up on this matter.","我们会跟进此事"],
    ["We will follow up with you tomorrow.","我们明天与您跟进"],
    ["We will keep you posted on the progress.","我们会随时向您通报进展"],
    ["Please let us know if you need any further assistance.","如需更多帮助请告知"],
    ["We are on top of this issue.","我们正在处理此事"],
    ["We will take immediate action.","我们将立即处理"],
    ["The issue has been resolved.","问题已解决"],
    ["Please confirm that the issue is resolved.","请确认问题已解决"],
    ["We confirm the matter has been closed.","我们确认此事已了结"],
    ["Thank you for your patience and understanding.","感谢您的耐心与理解"],
    ["We appreciate your understanding in this matter.","感谢您对此事的理解"],
  ]},
  // __UNITS__
];

(function () {
  var BOOK_ID = 'ship';
  var BOOK_NAME = '船用英语（航运/货代）';
  var EXAM = 'shipping';
  var words = {};
  var units = [];
  var widSeq = 0;
  var unitSeq = 0;
  function enWordId() { return 'sh_' + (widSeq++); }
  window.SHIP_UNITS.forEach(function (u, i) {
    unitSeq++;
    var unitId = (u.kind === 'phrase' ? 'ship_p' : 'ship_u') + unitSeq;
    var wordIds = [];
    (u.list || []).forEach(function (it) {
      var id = enWordId();
      var en = it[0], zh = it[1];
      // 第 3 项起为英文别名/全称（如缩写 ETA 的全称），反向测试与详情中都会识别/展示
      var aliases = it.slice(2).map(function (x) { return String(x).trim(); }).filter(function (x) { return x; });
      var w = {
        id: id, headword: en, phonetic: '', pos: '',
        examType: EXAM, bookId: BOOK_ID, unit: unitSeq - 1,
        senses: [{ meaning: zh }], collocations: [], tips: [], synonyms: []
      };
      if (aliases.length) w.aliases = aliases;
      words[id] = w;
      wordIds.push(id);
    });
    units.push({ id: unitId, name: u.name, wordIds: wordIds });
  });
  var allWordIds = [];
  units.forEach(function (u) { u.wordIds.forEach(function (w) { allWordIds.push(w); }); });
  window.SHIP_BOOK = {
    id: BOOK_ID, name: BOOK_NAME, examType: EXAM, source: 'builtin',
    units: units, wordIds: allWordIds
  };
  window.SHIP_WORDS = words;
})();
